# Schema for the configuration files of the Auto Alter module.
auto_alter.settings:
  type: config_object
  label: 'Auto Alter Config'
  mapping:
    endpoint:
      type: string
      label: 'Endpoint'
    credential_provider:
      type: string
      label: 'Credential Provider'
    credentials:
      type: mapping
      label: 'Credentials'
      mapping:
        config:
          type: mapping
          label: 'Auto Alter Credentials'
          mapping:
            openai_api_key:
              type: string
              label: 'OpenAI API Key'
            azure_api_key:
              type: string
              label: 'Azure API Key'
            azure_api_base:
              type: string
              label: 'Azure API Base URL'
            azure_organization:
              type: string
              label: 'Azure OpenAI Organization'
            azure_api_version:
              type: string
              label: 'Azure API Version'
        key:
          type: mapping
          label: 'Auto Alter Credentials with Key Module'
          mapping:
            api_key_key:
              type: string
              label: 'API Key (Key Module)'

    service_selection:
      type: string
      label: 'Service Selection'
    openai_prompt:
      type: string
      label: 'Predefined OpenAI Prompt'
    azure_prompt:
      type: string
      label: 'Predefined Azure OpenAI Prompt'
    status:
      type: boolean
      label: 'Status'
    suggestion:
      type: boolean
      label: 'Suggestion'
